### ISSUE TITLE
Feature-request: WSL support 

### ISSUE THREAD

**Issue by vaib25vicky** [bytebutcher/burp-send-to#5]
Is it possible to send requests to tools inside WSL? I'm trying to do so but still haven't figure it out yet. 

The command when run in windows will successfully connects to tools inside WSL

`cmd /c start cmd /k wsl	/home/vicky/work/bin/ffuf -v`

But burp-send-to is not able to send requests to the WSL. 

It would be cool if burp-send-to can do that because lot of people prefer to keep their tools/dev env in WSL

**Comment by bytebutcher** [comment]
Hi @vaib25vicky, thanks for reporting this issue. I'll look into it and keep you posted!

**Comment by vay3t** [comment]
For reference @bytebutcher  you can see the following code https://github.com/nscuro/bradamsa-ng/tree/master/src/main/java/com/github/nscuro/bradamsang/wsl

I also want to add in this issue (if I need to open another one, you can tell me) is the existence of the "copy" button, sometimes one only needs to have the command without having to execute it.

By the way, your tool is very good, I think it would be useful if you add the command for ffuf, dirsearch, Arjun, as native in the plugin. It would also be useful to have a configuration file to export and import, this way when you have to install burp from a new computer it will not be necessary to configure all the commands again.

**Comment by bytebutcher** [comment]
Hi @vay3t, thanks for the update! Yes, adding ffuf, dirsearch, arjun sounds like a good idea! I'll also look into providing a "copy" button. Regarding "Import" and "Export" - this is already possible (see documentation). If you have any problems please let me know.

@vaib25vicky: sorry for the late response. i need to setup a native windows environment for testing this. I will look into this matter on the weekend and let you know about WSL support.

**Comment by bytebutcher** [comment]
@vaib25vicky: i can confirm the problem. I've tried a few things and you may solve it using a wrapper script.

See the following link in section WSL for more information: https://github.com/bytebutcher/burp-send-to/wiki/Examples

@vay3t: I'll create a new ticket for the "copy/duplicate" feature and close this ticket for now.
