### ISSUE TITLE
It will be Awesome If There Are Placeholders To Replace e.g. Status Code Of Response , Content Length Of Response etc

### ISSUE THREAD

**Issue by 0xAwali** [bytebutcher/burp-send-to#6]
There Are not Placeholders To Replace Response Of The Current Request e.g. If I Want To Use FFUF Tool To Fuzz Directory So FFUF Give Us -fc Option To Filter Specific Status Codes From Response
So It Will Be Awesome If You Add Placeholders To Replace Response e.g.
%SC   Response Status Code Of Current Request
%L      Content Length Of Current Request
and You Can Add More

**Comment by bytebutcher** [comment]
Hi @0xAwali,
thanks for your report. I'm looking into it. If you have also any other placeholders besides %SC and %CL in mind please let me know!

**Comment by 0xAwali** [comment]
Actually Not , I Think %SC , %CL Are The Most Useful For Us

**Comment by bytebutcher** [comment]
Hey there, i've uploaded a new version which contains two new placeholders:'
* HTTP Status Code %O
* HTTP Content Length %L
You can download the new verison here: https://github.com/bytebutcher/burp-send-to/releases/download/v1.6/burp-send-to-extension-1.6.jar
Please let me know if you experience any problems when using the new version!
