### ISSUE TITLE
Feature request: Authorization header shortcut 

### ISSUE THREAD

**Issue by Regala** [bytebutcher/burp-send-to#9]
Hi @bytebutcher ! %C is already super useful, however nowadays many apps use `Authorization: Bearer token{...}`. Would be awesome if we could use that, similar to how %C for cookie works e.g. %B (bearer token). 

Alternatively a more flexible implementation could be done allowing any header to be invoked in the command, something like:
%H{Authorization} -> would fetch the Authorization header
%H{Referer} -> would fetch the Referer header
etc

Thanks!

**Comment by bytebutcher** [comment]
Hi @Regala ! Thanks for your feature request! That sounds like a nice idea! I'll definitely look into it! Currently i'm a bit swamped by other kind of work so it might take a while to implement. Another thing which might work for you is parsing the desired header in your shell/python script. Here's an example: 

**Send-To Context Menu Entry:**
```
Name: parse_header.sh
Command: /path/to/script/header.sh %E
```

**header.sh**
```
#!/bin/bash
# first parameter: e.g. /tmp/burp_14295605999789358076.snd
header_file="${1}" 
# parse the user agent
user_agent="$(grep -m1 "User-Agent: " "${header_file}")"
if [ -z "${user_agent}" ] ; then
        echo "ERROR: No user agent found in header!" >&2
        exit 1
fi
# retrieve the actual user agent value
user_agent_value="$(echo -n "${user_agent}" | cut -d: -f2-)"
echo ${user_agent_value}
```

**Comment by Regala** [comment]
Oh awesome, that's a good workaround!

Cheers!
